services:
  - type: web
    name: irofumi
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: irofumi-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: irofumi-db
    databaseName: irofumi_production
    user: irofumi